# Default Config File for PureEntitiesX

# set where entities can spawn e.g ["world", "flat"], or leave empty to allow entities to spawn in any level
enabledworlds: []

# set how often the spawn and despawn task will be trigered
spawn-task:
  trigger-ticks: 300
  use-block-light: false
  use-sky-light: false

# after how many ticks an entity gets despawned (if not tamed)
despawn:
  after-ticks: 72000

# configuration of panic mode for some entities
panic:
  enabled: true
  ticks: 100 # how long is an entity in panic mode

# task definitions - to have full functionality, enable all!
tasks:
  spawn: true # set to true to enable spawn/unspawn tasks
  async: true # set to true for mob equipment working and relogging tamed entities working
  looking: true # set to true to enable entity interaction and enderman looking detection e.g.

# when set to true the creeper will explode and also destroy blocks
creeper:
  block-breaking-explosion: false

breeding:
  emit-love-particles-constantly: true

# describes the distances that are used for specific actions
distances:
  interact: 3 # defines until which distance an interaction with an entity is possible
  find-partner: 49 # defines whe maximum distance when love mode is active and is searching for another partner
  tamed-teleport: 20 # defines how many blocks the player can move until the tamed entity teleports to it's owner (when not sitting)
  tamed-follow-player: 14 # defines the distance between owner and tamed entity when it stops wandering around and get back to player

ticks:
  block-interest: 100 # defines how many ticks pass by before the block of interest check kicks in

idle:
  chance: 80 # 20 percent of idle after walking around
  min-idle: 100 # minimum idle in ticks
  max-idle: 500 # max idle in ticks
  time-between-idle: 20 # time that has to pass at least between each idling status in seconds

# please only tune the following when you know what you're doing ;)
performance:
  check-target-tick-skip: 5 # the lower the value the more performance it takes
  check-interactive-ticks: 10 # how often does the plugin check if an interactive button is displayed - the lesser the value the more performance is needed
  check-interactive-correction: true # setting this to true the interactive button finding is a lot better but more unprecise and consumes more performance
  check-enderman-looking: 10 # how often does the plugin check if a player looks at an enderman
  check-pickup-loot: 10 # how often do entities look after things they can pick up (configure ticks between checks)